apiVersion: v1
kind: Service
metadata:
  name: kubebit-core
  labels:
    app.kubernetes.io/name: kubebit-core
    app.kubernetes.io/instance: kubebit
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8801
      targetPort: http          
  selector: 
    app.kubernetes.io/name: kubebit-core
    app.kubernetes.io/instance: kubebit
    app.kubernetes.io/component: core