apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    "app.kubernetes.io/name": busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      "app.kubernetes.io/name": busybox
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": busybox
    spec:
      containers:
        - name: busybox
          image: "busybox:latest"
          args:
            - /bin/sh
            - -c
            - |
              while true; do
                echo -e "HTTP/1.1 200 OK\n\n$(date)" | nc -l -p 8000 -q 1
                sleep 5
              done
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP