apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebit-core
  labels:
    app.kubernetes.io/name: kubebit-core
    app.kubernetes.io/instance: kubebit
    app.kubernetes.io/component: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi